name: Checks

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
      CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run unit tests and generate the coverage report
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out
          verbose: true
          flags: unittests

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
      CGO_CFLAGS: "-O -D__BLST_PORTABLE__"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

      - name: Lint
        run: make lint

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD
